### ISSUE TITLE
Function get_nearest_neighbors is not working yet

### ISSUE THREAD

**Issue by hadelasmi** [facebookresearch/fastText#1040]
Hello everyone, 
I'm trying to work with Fasttext-0.9.1, the following function " model.get_nearest_neighbors " doesn't work anymore. 
Here is what it goes when I try it : '_FastText' object has no attribute 'get_nearest_neighbors'

Is there any other function to see the neighbors or similar words of a word?

Thank you for the help !

**Comment by ap-mannion** [comment]
!up

**Comment by wikithink** [comment]
!up
