### ISSUE TITLE
Python Optimal Transport issue in unsup_multialign.py

### ISSUE THREAD

**Issue by mamprogr** [facebookresearch/fastText#950]
Hi,
When I try to do:
./unsup_multialign.py --lglist en-fr-ar
It says:
```
AttributeError: module 'ot' has no attribute 'gromov_wasserstein'
```
To solve it, I changed https://github.com/facebookresearch/fastText/blob/0c6db7c2d6ba9e0ff81713ed9f50c3142e4ba700/alignment/unsup_multialign.py#L70 to be ```M = ot.gromov.gromov_wasserstein(...)```

Now it says:
```
Computing initial bilingual apping with Gromov-Wasserstein...
init fr
Traceback (most recent call last):
  File "./unsup_multialign.py", line 190, in <module>
    TRANS[i] = gromov_wasserstein(embi, emb0, C0)
  File "./unsup_multialign.py", line 70, in gromov_wasserstein
    M = ot.gromov.gromov_wasserstein(C1,C2,np.ones(N),np.ones(N),'square_loss',epsilon=0.55,max_iter=100,tol=1e-4)
  File "/home/nlp/.local/lib/python3.6/site-packages/ot/gromov.py", line 343, in gromov_wasserstein
    return cg(p, q, 0, 1, f, df, G0, armijo=armijo, C1=C1, C2=C2, constC=constC, **kwargs)
  File "/home/nlp/.local/lib/python3.6/site-packages/ot/optim.py", line 246, in cg
    alpha, fc, f_val = solve_linesearch(cost, G, deltaG, Mi, f_val, reg=reg, M=M, Gc=Gc, **kwargs)
TypeError: solve_linesearch() got an unexpected keyword argument 'epsilon'
```
The installed package is POT-0.6.0.
How to solve it?
Thanks.

**Comment by mamprogr** [comment]
I downgraded to POT-0.4.0 and now it is working.
1. Can you please update to code to work with POT-0.6.0?
2. Now, it outputs a lot of: ```Warning: numerical errors at iteration 0```, is it normal?

**Comment by newdaylqt** [comment]
I meet the same problem with POT-0.7.0.
Further, I check the codes in POT-0.4.0 and POT-master, and find that the old `ot.gromov_wasserstain` is almost the same as `ot.gromov.entropic_gromov_wasserstain` now except for adding an initialization step.

You can see the codes at the following links:
[master](https://github.com/PythonOT/POT/blob/master/ot/gromov.py)
[0.4.0](https://github.com/PythonOT/POT/blob/0.4.0/ot/gromov.py)

But still I got "Warning: numerical errors at iteration 0" and later these numerical errors caused "Intel MKL ERROR: Parameter 4 was incorrect on entry to DLASCL." and "numpy.linalg.LinAlgError: SVD did not converge". I think it is indeed a bug to be fixed.
